### PR TITLE
Enable SPF

### PR DESCRIPTION
**Pull request by ignisf**
As per

https://github.com/trusteddomainproject/OpenDMARC/blob/9cebf724d601452d1a671ed5331551dbc18df83a/opendmarc/opendmarc.conf.sample#L384

### CODE REVIEW

**Review by tyranron — APPROVED** [review]
@ignisf thanks!

I've added `libspf2` to the image. Similar to what Alpine packages do:
https://git.alpinelinux.org/aports/tree/community/opendmarc/APKBUILD#n41

**Comment by tyranron** [comment]
Released as [1.4.2-r35](https://github.com/instrumentisto/opendmarc-docker-image/releases/tag/1.4.2-r35).

**Comment by ignisf** [comment]
thank youuu! ^_^

**Comment by schildbach** [comment]
I'm a bit puzzled about this PR. I've been using `SPFSelfValidate = true` for a while and it seemed to work with `1.4.2-r34` already (no errors printed to logs). Is this PR implying that the option has been silently ignored up to now?

**Comment by schildbach** [comment]
It seems this is indeed the case. After applying this patch, OpenDMARC starts adding an `Authentication-Results` header for SPF.

However, I always get "fail" for SPF, even for my own domains which I know should pass. Sadly, OpenDMARC doesn't log any specifics. I believe the problem is caused by the incoming IP address being swallowed by docker-proxy (and in my case a reverse proxy too). Instead, SPF is evaluated against the internal address of docker-proxy which can't pass.

How do you handle this problem?

**Comment by ignisf** [comment]
> I'm a bit puzzled about this PR. I've been using `SPFSelfValidate = true` for a while and it seemed to work with `1.4.2-r34` already (no errors printed to logs). Is this PR implying that the option has been silently ignored up to now?

Yes, it was ignored up until now and SPF validation was silently not performed. (tbh this is borderline security vulnerability-level bug in opendmarc IMO)

> However, I always get "fail" for SPF, even for my own domains which I know should pass.

I am already using the new image in production, and SPF validation is passing.

```
Return-Path: <XXX@gmail.com>
Delivered-To: XXX@yyy.org
Received: from xxx.yyy.org ([127.0.0.1])
	by xxx.yyy.org with LMTP
	id mZniKCFK12X5ewAAibQPJw
	(envelope-from <XXX@gmail.com>)
	for <xxx@yyy.org>; Thu, 22 Feb 2024 15:20:33 +0200
Received: from mail-qt1-x829.google.com (mail-qt1-x829.google.com [IPv6:2607:f8b0:4864:20::829])
	(using TLSv1.3 with cipher TLS_AES_128_GCM_SHA256 (128/128 bits)
	 key-exchange X25519 server-signature ECDSA (prime256v1) server-digest SHA256)
	(No client certificate requested)
	by xxx.yyy.org (Postfix) with ESMTPS id CD155A05F6
	for <XXX@yyy.org>; Thu, 22 Feb 2024 13:20:32 +0000 (UTC)
Authentication-Results: opendmarc; dmarc=pass (p=none dis=none) header.from=gmail.com
Authentication-Results: opendmarc; spf=pass smtp.mailfrom=gmail.com
Authentication-Results: opendkim;
	dkim=pass (2048-bit key; unprotected) header.d=gmail.com header.i=@gmail.com header.a=rsa-sha256 header.s=20230601 header.b=hqWS+Tda;
	dkim-atps=neutral
```

Config here:

```
UserID                  opendmarc:opendmarc
Socket                  inet:8893

Syslog                  Yes

AuthservID              opendmarc
TrustedAuthservIDs      xxx.yyy.org
FailureReports          false
FailureReportsOnNone    false
SPFIgnoreResults        true
SPFSelfValidate         true
MilterDebug		-1
```

**Comment by tyranron** [comment]
@schildbach 

>  I believe the problem is caused by the incoming IP address being swallowed by docker-proxy (and in my case a reverse proxy too). Instead, SPF is evaluated against the internal address of docker-proxy which can't pass.
>
> How do you handle this problem?

We do keep our receiving mail servers in `hostNetwork: true` for the very same reason.

I think you can also experiment with [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) if your receiving mail server supports it. It may work as well. However, I had no success with it using Postfix.

**Pull request merged**
